/*
 * This source file was generated by the Gradle 'init' task
 */
package houserobber;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    int[] nums;
    App classUnderTest;
    @BeforeEach
    public void setUp(){
        nums = new int[]{2, 7, 9, 3, 1};
        classUnderTest = new App();

    }

    @Test
    void testDpSolutionReturnsCorrectAnswer() {
        int actual = classUnderTest.dpSolution(nums);

        assertEquals(12, actual);

    }

    @Test
    void testOptimizedDpSolutionReturnsCorrectAnswer(){
        int actual = classUnderTest.optimizedDpSolution(nums);

        assertEquals(12, actual);
    }




}
