/*
 * This source file was generated by the Gradle 'init' task
 */
package twosum;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void mapSolutionReturnsCorrectAnswer() {
        App app = new App();
        int[] nums = new int[]{2,7,11,15};
        int target = 9;

        assertArrayEquals(new int[]{0,1}, app.twoSumMap(nums, target));
    }
}
